# Gitleaks configuration for MMOps
# This file customizes secret detection rules

[allowlist]
  # Allow specific test files and config files
  paths = [
    "test_secret.env",
    "test.env",
    "docker-compose.yml",
    "Dockerfile"
  ]
  
  # Allow specific patterns in documentation and config
  regexes = [
    "sk_test_.*",
    "sk_fake_.*", 
    "your_.*_here",
    "example_.*",
    "postgresql://.*:password@.*",
    "postgres://.*:password@.*"
  ]

# Custom rules for MMOps-specific patterns
[[rules]]
  id = "mmops-api-key"
  description = "MMOps API Key"
  regex = '''(?i)(api[_-]?key|apikey)\s*[=:]\s*['"]?[a-z0-9]{32,}['"]?'''
  tags = ["api", "key"]
  entropy = 3.5

[[rules]]
  id = "mmops-database-url"
  description = "MMOps Database URL"
  regex = '''(?i)(database[_-]?url|db[_-]?url)\s*[=:]\s*['"]?[a-z]+://[^'"]+['"]?'''
  tags = ["database", "url"]
  entropy = 3.0